### ISSUE TITLE
DeEPsnap: human essential gene prediction by integrating multi-omics data

### ISSUE THREAD

**Issue by Ahmed-Ali88** [wjxiao2020/DeEPsnap#1]
Dear author,
I am a newbie in the field of bioinfo, Thank you for your research.I am trying to replicate your experiment for a class project so I appreciate you helping me with this.
 so I don't have much experience in data finding. May you give me the download link for the data you used from DEG 
 
essential gene database [http://tubic.tju.edu.cn/deg/.](http://tubic.tju.edu.cn/deg/) this link give me error 
 I appreciate your help.

**Comment by wjxiao2020** [comment]
Hi Ahmed, I just found this issue you opened. I have replied this to you through email. But maybe this will be helpful for other people as well: the newly updated link for the DEG database is http://origin.tubic.org/deg/public/index.php
